### ISSUE TITLE
AJAX loading GIF background

### ISSUE THREAD

**Issue by thecashewtrader** [sbakht/halal-competitions-frontend#3]
ٱلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ ٱللَّٰهِ وَبَرَكَاتُهُ
A great website and a great project.
I was wondering if the AJAX loading GIF's background could be made transparent instead of hardcoding it.
![image](https://user-images.githubusercontent.com/81344401/128622167-5bb136e0-3d78-49a9-8075-f423496fb659.png)
![image](https://user-images.githubusercontent.com/81344401/128622176-c81d0571-8cef-4d12-aff4-e3f44a06b67d.png)
This would allow it to work better with custom css and/or darkmode addons.

**Comment by sbakht** [comment]
Walaykum Assalam wa Rahmatullahi wa barakatuhi
Good idea. If you have a loader suggestion, ill take it. Or ill find one sometime
